workflows:
  version: 2
  build-deploy-stage:
    jobs:
      - build
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: staging
  build-deploy-prod:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
version: 2
jobs:
  build:
    working_directory: ~/bowling
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://austinbrown@localhost/bowling_db?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: austinbrown
          POSTGRES_DB: bowling_db
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install virtualenv
            virtualenv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
            - ".env"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            . env/bin/activate
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  deploy-stage:
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://austinbrown@localhost/bowling_db?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: austinbrown
          POSTGRES_DB: bowling_db
    steps:
      - checkout
      - run:
          name: Deploy Staging to Heroku Staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGE.git staging
  deploy-prod:
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://austinbrown@localhost/bowling_db?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: austinbrown
          POSTGRES_DB: bowling_db
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku Production
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
