version: 2
jobs:
  build:
    working_directory: ~/bowling
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://austinbrown@localhost/bowling_db?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: austinbrown
          POSTGRES_DB: bowling_db
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install virtualenv
            virtualenv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
            - ".env"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            . env/bin/activate
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
