# Generated by Django 2.0.7 on 2018-07-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0002_auto_20180709_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='current_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='current_player_index',
            field=models.IntegerField(default=0),
        ),
    ]
