# Generated by Django 2.0.7 on 2018-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0007_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
